.gometalinter.json
README.md
cfg/app.go
resolve/glob/glob_test.go
storage/postgres/build.go
storage/postgres/postgres_test.go
storage/verify.go

Goreportcard

---

README.md

- reduce logo size
- move content to the top
- move example repository to the bottom

readme: improve formatting

---

.editorconfig

I was trying to work on this and noticed that my tabs are actually spaces, and decided to fix it.

fix editorconfig since `tabs` is wrong need to use `tab`

---

internal/command/helpers.go
internal/command/init_app.go
internal/command/init_bashcomp.go
internal/command/init_db.go
internal/command/init_repo.go
internal/command/ls_apps.go
internal/command/ls_inputs.go
internal/command/ls_outputs.go
internal/command/show.go
internal/command/status.go
internal/command/verify.go
repository.go

- use exitOnErr functions when possible,
- improve error message when repository config file could not be found

Improve error handling in command implentation

---

.circleci/config.yml

ci: update golangci lint to 1.28.1

ci: update golangci lint to 1.28.1

---

taskstatusevaluator.go

Updating the implementation to match the comment (and fix the problem)

Fix wrong input string being recorded against run

---

internal/upload/docker/docker.go
internal/upload/docker/docker_test.go

**This is a cherry-pick of https://github.com/simplesurance/baur/pull/224 for master**
Closes #225 
-------
"docker login" supports to specify registry per hostname and as URL.
If the credentials used the URL, baur was not able to find the credentials when
the push was done using only the hostname of the registry server.
This is a common usecase for GCR auth per json_key.
The authentication logic was also approved in the following ways:
- registry URLs with ports are supported,
If a registry was authenticated with the default port 5000), and no port is
given for the registry url in the app config, the credentials for the
registry with the default port is used
- the credentials for the default registry (index.docker.io) are only used when
the host of the specified registry matches or no …

docker: improve choosing credentials for registry, support URLs

---

.circleci/config.yml

CI: Update Golang & golangci-lint

CI: Update Golang & golangci-lint

---

cfg/app.go
cfg/app_test.go
cfg/dockerimageoutput.go
cfg/dockerimageregistryupload.go
cfg/fielderror.go
cfg/filecopy.go
cfg/fileinputs.go
cfg/fileoutput.go
cfg/gitfileinputs.go
cfg/golangsources.go
cfg/include.go
cfg/includedb.go
cfg/input.go
cfg/inputinclude.go
cfg/inputincludes.go
cfg/output.go
cfg/outputinclude.go
cfg/outputincludes.go
cfg/repository.go
cfg/s3upload.go
cfg/task.go
cfg/taskdef.go
cfg/taskinclude.go
cfg/taskincludes.go
cfg/tasks.go

- delete some unused methods
- make methods private if they do not need to be public

Cleanup the cfg package

---

cfg/app.go
cfg/cfg.go
cfg/include.go
cfg/task.go
cfg/taskinclude.go
internal/command/show.go

See the commit messages for details.
It's a bunch of unrelated small improvements

various small improvements

---

internal/command/diff_inputs.go
internal/command/run.go
internal/command/term/format.go
internal/format/csv/csv.go
internal/fs/fs.go
internal/resolve/gosource/gosource.go
internal/upload/filecopy/filecopy.go
pkg/cfg/task.go
pkg/cfg/taskinclude.go

fix spelling in documentation and error messages

fix spelling in documentation and error messages

---

internal/command/run.go
internal/upload/docker/docker.go
pkg/baur/baur.go
pkg/baur/diff.go
pkg/baur/inputfile.go
pkg/baur/inputresolver.go
pkg/baur/output.go
pkg/baur/outputdockerimage.go
pkg/baur/outputfile.go
pkg/baur/storage.go
pkg/baur/task.go
pkg/baur/taskrunner.go
pkg/baur/taskstatusevaluator.go
pkg/baur/uploader.go
pkg/cfg/resolver/gotemplate.go

improve godoc

---

README.md

- more baur 2.0 informations
- restructuring
- a GIF that demonstrates baur will be added in a following PR

readme: add more information about baur 2.0 and other improvements

---

README.md

add an asciinema gif of baur 2.0 to the README

readme: add asciinema image with link

---

pkg/storage/postgres/insert.go

When multiple baur instances ran in parallel and were inserting inputs it
happened that a postgresql deadlock occurred.
The happened deadlock is exactly the one explained in
https://www.postgresql.org/docs/current/explicit-locking.html#LOCKING-DEADLOCKS.
To prevent those deadlocks, the inputs are now sorted before insert.
This prevents the described deadlock scenario.
This fixes the postgresql error:
2022-02-25 09:37:26 UTC ERROR:  deadlock detected
2022-02-25 09:37:26 UTC DETAIL:  Process 158747 waits for ShareLock on
transaction 44098; blocked by process
157931.
Process 157931 waits for ShareLock on transaction 44099; blocked
by process 158747.
Process 158747:
INSERT INTO input_file (path, digest)
[...]

postgres: prevent db deadlock on input insert with multiple instances

---

internal/fs/fileglob.go

Update to use doublestar's WithFilesOnly instead of our own filter

---

.github/workflows/build.yml
.github/workflows/golangcilint.yml
.github/workflows/test.yml
internal/command/diff_inputs.go
internal/command/init_app.go
internal/command/init_db.go
internal/command/init_include.go
internal/command/init_repo.go
internal/command/ls_apps.go
internal/command/ls_inputs.go
internal/command/ls_outputs.go
internal/command/ls_runs.go
internal/command/run.go
internal/command/show.go
internal/command/status.go
internal/command/upgrade_configs.go
internal/command/upgrade_db.go
internal/fs/fs.go
pkg/baur/inputresolver.go
pkg/baur/inputresolver_test.go
pkg/baur/loader.go
pkg/cfg/include.go

update go & golangci-lint, fix new issues found by golangci-lint

ci: update go & golangci-lint

---

internal/exec/command.go
internal/exec/command_linux_test.go

If the output of a command was streamed via the logFn function and the output did not contain newlines after latest each 512Kb, the execution failed. This happened because when splitting the output in lines failed, the PipeReader was closed, causing all writes to the MultiWriter to fail. Which in turn causes writes from the process to stdout and stderr fail.
Handle this error case gracefully. Streaming output is for debugging purposes and not required for the result.
If the line scanner returns an error, log it and discard all further output of the logreader.
If discarding the output fails, the logReader is closed with an error. This should not happen, if it does and the logreader would not be closed, it would cause the process to block forever.
A testcase for the error scenario is added.

exec: fix: execution fails when output is streamed and lines are >=512KB

---

pkg/baur/inputresolver.go

Move the code for querying the needed information to create an InputFile to separate methods.
That makes it easier to follow.

inputresolver: refactor code for creating an InputFile

---

internal/set/set.go
internal/vcs/git/repository.go
internal/vcs/git/trackedobjects.go
pkg/baur/loader.go

We use in multiple places a map with empty struct values as set.
Add a simple Set datatype that we can be used instead.
This allows to remove duplication and simplify the code in multiple places.
(More occurrences will be changed to use the Set datatype in follow-ups)

introduce set datatype

---

internal/command/command_test.go
internal/command/diff_inputs.go
internal/command/diff_inputs_test.go
internal/command/ls_inputs.go
internal/command/ls_outputs.go
internal/command/ls_runs.go
internal/command/run_test.go
internal/command/status.go
internal/command/upgrade_configs_test.go

```
command: usage: improve --quiet flag description
command: print header in csv output format if --quiet is not passed
```
Closes #526

command: print header in csv output format if --quiet is not passed

---

.github/workflows/golangcilint.yml
go.mod
pkg/storage/postgres/insert_test.go
pkg/storage/postgres/query_test.go

update go & golangci-lint

---

internal/resolve/gosource/gosource.go

According to the godoc of the packages.Package struct the GoFiles, OtherFiles and EmbedFiles contain absolute paths.
Do not call filepath.Abs() unnecessarily for each of them.

gosource: remove unnecessary filepath.Abs call
