simplesurance/baur

app.go, command/helpers.go
```
commit 4c4115cc18f357bfdf9e16ef2e673c8f12b77287 (HEAD -> dedupargs, origin/dedupargs)
Author: Fabian Holler <fabian.holler@simplesurance.de>
Date:   Thu Dec 13 17:23:56 2018 +0100
cmd: deduplicate the passed appnames and paths
Deduplicate the returned list of discovered applications in mustArgsToApps().
This prevents that an operation is run multiple times if an application is
specified multiple time on the commandline, to e.g. baur build.
commit 37dae640475521d588cc0d71248cbb4a7120742c
Author: Fabian Holler <fabian.holler@simplesurance.de>
Date:   Thu Dec 13 17:31:02 2018 +0100
app: allocate map with required capacity in pathsToUniqFiles()
We know the max. number of elements that we store in the map in advance,
therefore allocate it with the needed capacity to save alloc operations. …
```
=> Deduplicate application names and paths passed to the commandline

README.md
docs: update readme
Remove the "go get" instruction from the README, only suggest to install baur
from a release archive. When baur is installed via "go get" the intern version
variable can not be set to the current commit.
When somebody submits later a bugreport it won't be possible to figure out from
which commit his baur version was build which makes debugging much harder.
Also add subsection in Quickstart to make it easier readable and change the
wording slightly.
=> readme: remove installation instruction via "go get"

git/git.go
Git has by default the 'core.quotePath' option enabled.
This caused that git ls-files printed some filenames enclosed in quotes and with
escaped characters.
Opening files were the quotePath option took effect failed because no file with
that name existed.
Disable the quotePath git option when running git ls-files to get the raw
filename.
=> resolve: resolving unusual filenames as gitfile input failed

build.go, cfg/app.go, cfg/repository.go, command/build.go, command/flag/buildstatus.go, command/helpers.go
.app.toml files are now also valid if they have no [Build] section defined.
This allows to use baur for discovering apps in a repository without building
them with baur.
"baur ls apps" shows the status "Build Command Undefined" for apps that have no
[Build] section.
When "baur build" is called, apps without a [Build] section are skipped.
The "baur build" output is now more similar with and without "--force" option.
In both cases it now lists the applications that will be build before starting
the build.
If --force is passed, apps that will be build will be shown with Pending status.
The application list that is printed by "baur build" is now also sorted.
=> cfg: make the [Build] section in the .app.toml file optional

app.go, cfg/app.go, cfg/cfg.go, cfg/include.go, cfg/repository.go, command/init_include.go, command/show.go, fs/fs.go, fs/fs_test.go, log/log.go, repository.go
This PR adds support for specifying build input in include files (https://github.com/simplesurance/baur/issues/76).
The `.baur.toml` got a new setting `include_dirs` to specify a list of directories that can contain include files.
The command `baur init include` creates a new exemplary include file.
The include file can contain multiple `BuildInput` sections, with the same members then in the `.app.toml` plus an additional `id` field.
The `id` field is used to reference the include section in an `.app.toml` file.
Example Include file:
```toml
[[BuildInput]]
id = "go_app_build_inputs"
[BuildInput.Files]
paths = [".app.toml", ".build.sh"]
[BuildInput.GolangSources]
environment = ["GOFLAGS=-mod=vendor","GO111MODULE=on"]
paths = ["."]
```
Use in `.app.toml` file:
```toml
name = …
```
=> Support to specify Build.Inputs in include files

upload/docker/docker.go
Instead of getting a list of all images, iterating through it and find the one
with imageID, use InspectImage and only retrieve the image information for the
specific image. It is more efficient.
=> docker: use InspectImage in Size()

fs/fs.go
```
fs: only return true from IsFile(), if it is a regular file
The function was returning true if the path was not pointing to a directory.
If it was a device file, symlink or socket it was returning true.
Change the function to only return true if it's a regular file.
```
=> fs: only return true from IsFile(), if it is a regular file

.circleci/config.yml, .gitignore, app.go, apploader.go, cfg_resolvers.go, fs/fs.go, git/git.go, git/state.go, internal/command/build.go, internal/command/helpers.go, repository.go, resolve/gitpath/gitpaths.go
```
Author: Fabian Holler
Committer: Fabian Holler
move discovering and loading Apps to AppLoader
The functionality to discover and load apps from configs is moved from the
Repository type to an own AppLoader type.
Author: Fabian Holler
Committer: Fabian Holler
decouple App from Repository
Remove the reference from the App to the Repository type.
This will make it easier to refactor App for implementing the task type.
Author: Fabian Holler
Committer: Fabian Holler
resolver: improve parameter names of gitpath resolver
Author: Fabian Holler
Committer: …
```
=> Decouple App and Repository, introduce AppLoader type

app.go, build.go, build/build.go, cfg/inputdef.go, cfg/inputinclude.go, internal/command/build.go, internal/command/ls_apps.go, internal/command/ls_inputs.go, internal/command/show.go, task.go
introduce Task type
Task represents the section with the same name in the .app.cfg file.
The fields and method relating to Inputs, Outputs and building an App are moved
to Task.
In the future baur will support to define multiple tasks per app.
Currently only one task name with the name "build" is supported.
=> Introduce baur.Task type

build.go, file.go, inputresolver.go, inputs.go, internal/command/build.go, internal/command/flag/buildstatus.go, internal/command/helpers.go, internal/command/ls_apps.go, internal/command/ls_inputs.go, resolve/gitpath/gitpaths.go, resolve/glob/glob.go, resolve/glob/glob_test.go, resolve/gosource/gosource.go, resolve/gosource/gosource_test.go, resolve/resolver.go, task.go
```
build: do not print 2 consecutive separator lines when no app needs to be build
remove BuildStatusBuildCommandUndefined
Task definitions in the config file must have a Command defined otherwise the
validation fails.
Remove the BuildStatusBuildCommandUndefined, it's not needed anymore.
refactor resolving inputs of a task
- Resolving inputs of a task is moved from the Task struct to an InputResolver
struct
- Inputs struct is introduced that has a caching method to calculate the total
input digest
- "baur build" will now always query the status of a build from the db, also
when "--force" or "--skip-uploads" is passed …
```
=> Refactor resolving inputs

.circleci/config.yml, internal/command/flag/buildstatus.go, internal/command/helpers.go, internal/command/ls_apps.go, internal/command/root.go, internal/command/status.go, loader.go
```
baur: add global parameter to disable colored output
circleci: update golangci-lint to 1.23.8
baur: introduce status command
- "baur status" shows the run status of tasks, same what "baur ls apps" did so
far but for tasks
- "baur ls apps" only shows static informations about apps now
- loader: when passing no args to LoadApps() or LoadTasks() it has the same
effect then passing '*'. This makes it easier to use from the command package.
apploader: add methods to load tasks
- rename AppLoader to Loader
- add method LoadTasks(), to load tasks that …
```
=> Support filtering by task names, add `baur status` command

app.go, cfg/app.go, cfg/repository.go
The $ROOT and $APPNAME variables can be specified in the Command field of the
.app.toml files and are resolved before execution.
The config version is incremented to 4.
This closes #152
=> cfg: support resolving $ROOT and $APPNAME variables in command field

format/csv/csv.go, format/format.go, format/table/table.go, internal/command/helpers.go, internal/command/init_app.go, internal/command/ls_apps.go, internal/command/ls_inputs.go, internal/command/ls_outputs.go, internal/command/ls_runs.go, internal/command/root.go, internal/command/run.go, internal/command/show.go, internal/command/status.go, internal/command/term/format.go, log/log.go
This PR:
- ensures all commands represent task and do not use the build terminology anymore,
- harmonizes the command code and make use of the recent improvements in all commands,
- fixes some smaller issues found on the go
See the commit messages for a full list of changes
=> Commands: harmonize command code, small changes to represent tasks instead of builds

internal/command/show.go, internal/command/term/color.go
```
show: show each File/GitFile/GolangSource input on a separate line
Showing all defined Input paths in the same line resulted in too long lines
which made the output hard to read.
Print one input element per line
command: change highlight color from green to magenta
Green color was also used to indicate success.
magenta blue instead of green for general highlighting to distinguish it better
from success indicators.
```
=> Improve show output formatting, change highlight color

cfg/app.go, cfg/golangsources.go, cfg/include.go, cfg/includedb_test.go, cfg/input.go, cfg/inputdef.go, cfg/inputinclude.go, cfg/taskdef.go, cfg/upgrade/v4/v4.go, inputresolver.go, internal/command/show.go
```
show: print Gosource BuildFlags and Tests fields
The "baur show" command was now displaying the new BuildFlags and Tests of
GolangGolangSources inputs, show them.
cfg: convert the GolangSources field in the app config to a slice
The GolangSources field consisted of multiple field and app configs only had a
single GolangSources element.
When includes that contained GolangSources definitions were merged with the app
config, the values of the includes were appended to the single GolangSources
definition.
This could cause that golangsources were evaluated for a path with wrong
Environment, BuildFlags or Tests settings.
Convert the GolangSources to a slice.
This allows to keep the settings from GolangSources …
```
=> cfg: change GolangSources field to be a slice

input.go, inputresolver.go, inputs.go, inputstring.go, internal/command/command_test.go, internal/command/ls_inputs.go, internal/command/run.go, internal/command/status.go, storage.go, taskstatusevaluator.go
```
command: rename --alt-input-str parameter to --lookup-input-str
The name makes it more clear that the input str is only used for lookups.
Fields and variable names are also adapted to the new name
simplify handling input Strings
Use the introduced Input interface to store Inputfiles and the inputString in
the same slice.
This simplifies the usage, conditional handling for the inputString can be
removed in many places.
InputString are now only added to Inputs if the string is not empty.
Previously InputString with an empty String value were added which made it
necessary to check later again if the String was empty or not.
In some places inputs.GetInputString().Exists() was called without checking if …
```
=> Improve input string handling

.golangci.yml, cfg/upgrade/v4/v4.go, cfgupgrade.go
- a '/v1' suffix was added to the import path of baur, adapt the goimports
local-prefix accordingly.
- fix the formatting of the import statements accordingly
=> golangci-lint: change local prefixes to v1 and fix imports

app.go, inputresolver.go, internal/command/init_app.go, internal/command/init_bashcomp.go, internal/command/init_repo.go, internal/fs/fileglob_test.go, internal/fs/fs.go, internal/testutils/repotest/repotest.go, internal/upload/filecopy/filecopy.go, internal/vcs/git/git.go, loader.go, repository.go
Use the functions from the "filepath" package instead of from the "path" package.
The functions in "filepath" are OS-independent, the functions in "path" are for
generic paths.
This closes #187.
=> use os independent filepath functions

cfg/app.go, cfg/taskdef.go, cfg/tasks.go, internal/command/show.go, internal/command/show_test.go
```
show: support to show information about a task
A taskname is the format <APP-NAME>.<TASK-NAME> can now be passed to "baur
show".
cfg: validate that the name of a task is not empty
```
This closes #172
=> show: support to show information about a task

internal/command/command_test.go
The testcase sets the environment variable envVarPSQLURL to a specific database
url.
Before the next testcase runs, the environment variable must be unset again.
If this is not done, the environment variable is still set when the next
testcase runs, the wrong database might be used which can cause test failures.
=> test: reset environment variable envVarPSQLURL when testcase finishes

internal/command/command_test.go
Restore the value before it was set in the testcase instead of setting it to an
empty string.
Setting it to an empty string still might change it's value and affect following
testcases
=> test: reset env var to old value instead of setting it to an empty string

internal/digest/digest.go, internal/digest/sha384/sha384.go, internal/digest/sha384/sha384_test.go
@StephenDiligent figured out, that creating a sha384 digest and converting
it's string representation back to a digest can fail with a "hash length is 95,
expected length 96" error.
If a calculated digest started with 0, the leading 0 was truncated from the
hash.
This happened because the hash was stored as big.Int, leading zeroes can be
omitted for an integer without changing the meaning. Truncating a zero from a
digest makes it invalid.
Fix this by using the helpers from the hex package to create a string
representation of the hash instead of big.Int.
A testcase is added for the bug.
The existing testcase are changed to compare digests via their string
representation instead of converting the Sum to a string on their own.
=> digest: fix: leading zero was truncating from sha384 string representation

digest/digest.go, digest/sha384/sha384.go, digest/sha384/sha384_test.go, git/git.go
```
gitfileinputs: error out when one of the paths did not match any files
Instead of passing the parameter "--error-unmatch" to "git ls-files",
"error-unmatch" was passed as pattern.
This caused that when a GitFileInput Paths list contained multiple elements, it
was sufficient that only one of the patterns matches files to not cause an
error.
When specified path does not match baur should fail with an error instead.
This fix is a backport from master.
digest: fix: leading zeroes were truncated from sha384 string representation
This is a backport of PR (#208).
@StephenDiligent figured out that creating a sha384 digest and converting it's
string representation back to a digest can fail with the error:
"hash …
```
=> 0.19.0 fixes

inputresolver_test.go, internal/command/show_test.go
```
inputresolver: add testcase
Add a testcase that ensures that an error is returned when the Optional flag for
GitFileInputs and FileInputs is set and one of the patterns in the Path slice
matches and another doesn't.
tests: add missing dbtest build tag
The show_test.go file is requiring a postgresql to be available but the dbtest
build tag was not set.
```
This closes #203. The described issue does not exist. It works as expected.
The PR adds only testcases to cover the described scenario.
=> inputresolver: add additional testcases

app.go, go.mod, internal/digest/digest.go, internal/digest/sha384/sha384.go, internal/fs/fileglob.go, internal/upload/docker/docker.go, internal/upload/filecopy/filecopy.go, internal/vcs/git/git.go, internal/version/version.go, repository.go, uploader.go, vendor/modules.txt
Fixes #211 
- using Golangs errors wrapper `fmt.Errorf %w` 
- `errors.Is` is used Golang standard `errors`
- Also remove `go.mod` and vendor directory
=> Remove using pkg/errors #211

cfg/app.go, internal/command/command_test.go, internal/command/diff_inputs_test.go, internal/command/show_test.go, internal/command/upgrade_configs_test.go, internal/command/util_test.go, internal/log/log.go, internal/log/testlogwrapper.go, internal/testutils/logwriter/logwrap.go
This PR redirects output that is generated during test execution to the log functions of `testing.T`.
Forwarding the output to the test logger allows `go test` to associate output with the associated testcases.
This makes it easier to debug issues when tests are failing.
So far a lot of the output generated during test execution was printed simply to stdout or stderr and `go test` showed it intermingled with output from other tests.
1. The log package is changed to support forwarding all output to the test logger
2. A wrapper io.Writer wrapper for the testlogger is introduced that can be used as stdin and stdout streams for the commands.
3. Testcases are adapted to change the logger and stdin/stdout streams to log via the test logger.
=> Tests: log all output of commands via the test logger

internal/command/diff_inputs_test.go, internal/command/util_test.go
```
tests: support validating exit codes when using initTest()
To be able to also use the initTest() function when the exit code of a command
needs to be validated it is refactored to set the exitFunc() to a function that
panics instead of calling t.Fatalf().
To panic() a struct is passed that contains the Exitcode with that exitFunc()
was called.
This allows to recover from the panic and validate if the exitCode is as
expected.
```
merge after https://github.com/simplesurance/baur/pull/218
=> tests: support validating exit codes when using initTest()

internal/command/command_test.go, internal/command/helpers.go, internal/command/init_app.go, internal/command/init_bashcomp.go, internal/command/init_db.go, internal/command/init_include.go, internal/command/init_repo.go, internal/command/ls_outputs.go, internal/command/ls_runs.go, internal/command/root.go, internal/command/run.go, internal/command/show.go, internal/log/log.go, internal/log/testlogwrapper.go
```
test: remove unnecessary overwrite of exitfunc
exitFunc() is already set by initTest() and is sufficient for the need of the
testcase
log: remove Fatal functions
remove the Fatalln and Fatalf functions from the logger.
Fatal errors should always result in a message to the users which should be
printed via the stderr stream.
The Fatal log functions were also not terminating the program via the exitFunc()
which caused different behaviors when they were run in testcases.
command: always use stdout/stderr streams
Use the stdout and stderr streams printing output from commands instead of
directly printing to stdout/stderr.
This …
```
=> Cleanup of the log package

internal/command/ls_apps.go
When then --fields and --status parameters were passed together to "baur ls
apps", the command printed no output.
The storage was not queried for the task therefore no task matched the specified
status and nothing was printed.
Ensure the storage is queried when --status is passed.
This is a backport of https://github.com/simplesurance/baur/pull/222 for version 0.x
=> baur ls apps: fix: no output when "-s" and "-f" flags are passed together (v0 backport)

internal/command/status.go, internal/command/status_test.go
When then --fields and --status parameters were passed together to "baur status", the command
printed no output.
The storage was not queried for the task,  therefore no task matched the specified status
and nothing was printed.
Ensure the storage is queried when --status is passed.
Closes #80
=> baur status: fix: no output when "-s" and "-f" flags are passed together

internal/command/status_test.go, loader.go, loader_specifiers.go
```
loader: fix paths containing dots not correctly interpreted
If an app or tasks were loaded by specifying a path and the path contained dots,
e.g. "../", the loader failed with the error that the specifier contained too
many dots.
This is fixed by first checking if a specifier is the path of an existing
directory that contains an .app.toml file, before interpreting it as app-name.
The loader was refactored to share more code between LoadTasks() and LoadApps().
Parsing the  specifiers is moved to an own function (parseSpecs()).
status: add testcases for handling arguments
Add testcases that ensure arguments are parsed and interpreted as expected by
"baur status".
These testcases mainly test the Loader …
```
=>  loader: fix paths containing dots not correctly interpreted

internal/command/build.go, upload/docker/docker.go, upload/docker/docker_test.go
```
build: remove support for BAUR_DOCKER_USERNAME, BAUR_DOCKER_PASSWORD env vars
Remove support for specifying docker registry username and password per
environment variable:
- settings credentials via environment variables can be insecure,
the docker configuration (docker login) offers a standardized and secure way
to specify credentials
- the implementation was not secure, it was only possible to specify a user and
password but not the url of the registry for which the credentials were used,
the user+password were tried to be used for every push that baur did to
every registry
docker: improve choosing credentials for registry, support URLs
"docker login" supports to specify registry per hostname and as URL. …
```
=> docker: improve credential handling, remove support for specifying docker credentials via env var

cfg/app.go, cfg/include.go, cfg/includedb.go, cfg/includedb_test.go, cfg/inputinclude.go, cfg/outputinclude.go, cfg/task.go, cfg/taskdef.go, cfg/taskinclude.go, cfg/taskincludes.go, inputresolver.go, internal/command/helpers.go, task.go
inputs: add .app.toml and included cfg files to inputs of a task
All config files that are parsed to load a Task are now automatically included
as the inputs of the task. This includes the included files.
Closes #84
=> inputs: add .app.toml and included cfg files to inputs of a task

internal/command/diff_inputs.go, internal/command/init_db.go, internal/command/ls_outputs.go, internal/command/ls_runs.go, internal/command/run.go, internal/command/show.go, internal/command/status.go
The commands were never closing the database connections that they acquired.
This was not an issue because most commands were only acquiring 1 connections,
when baur terminated the tcp connection was closed from the OS.
Closing the pgx connection also do not return any errors that could indicate
that previous operations failed like for writes to files.
The command functions were also invoked in testcases though. It happened that a
test run kept open more db connections then the psql server allowed, operations
failed with "FATAL: sorry, too many clients already".
Close database connections properly to prevent issues like this.
=> commands: close db connections explicitly

internal/command/diff_inputs.go, internal/command/ls_inputs.go, internal/command/ls_inputs_test.go, internal/command/storageinputwrapper.go
"baur ls inputs" can now be passed a task run ID to list all inputs of a stored
task run.
- The storageInput struct from the diff_inputs.go is reused for the "ls inputs"
implementation and moved to an own file.
- a simple testcase is added that runs "ls inputs" for a task, runs the task,
runs "ls inputs" for the stored task run and compares the outputs
Closes #129
=> ls inputs: support to list inputs of task runs

internal/command/diff_inputs.go, internal/command/diff_inputs_test.go
Update regex used to allow application names that contain a dash character.
Fix for https://github.com/simplesurance/baur/issues/236
=> 236-ALLOW-DASH-DIFF-INPUTS - Update diff inputs regex 

internal/command/diff_inputs.go
The "baur diff input" command was allowing to pass an arbitrary character after
a '^' in the parameters.
Every character after a '^' was interpreted as a '^' and had the same effect,
e.g: mail.build^^^ == mail.build^AbZ
Fix the syntax, only allow '^' to follow a '^' character in the parameters.
=> diff inputs: fix parameter validation: only allows '^' after a '^'

.circleci/config.yml
Use:
- go 1.15.6
- golangci-lint: 1.35.2
=> ci: update golang and golangci-lint

internal/command/diff_inputs.go, internal/command/ls_runs.go, storage/filter.go, storage/postgres/filters_sorters.go, storage/postgres/query.go, storage/postgres/query_test.go, storage/storage.go
These changes implement the suggestions made in the [Find most recent build with a specifc input-str](https://github.com/simplesurance/baur/discussions/235) discussion.
A couple of things to note:
- To be able to support filtering by an input URI value I needed to introduce a new query that included the `input.uri` field in the query's inner `SELECT DISTINCT ON` clause. Without adding the `input.uri` field only a single input would be returned by the inner SELECT statement and it may not have been the input we wanted to filter on. If the `input.uri` field was added to the existing query any queries that did not filter by input URI would return a row for each input which is not the desired behaviour. 
- I opted to add a `has-input-str` flag instead of the `has-input` flag mentioned in the …
=> Add input-str and limit filtering to ls runs command

cfg/app.go, cfg/app_test.go, cfg/dockerimageoutput.go, cfg/filecopy.go, cfg/fileoutput.go, cfg/include.go, cfg/includedb_test.go, cfg/s3upload.go, cfg/upgrade/v4/v4.go, internal/command/show.go, internal/testutils/repotest/repotest.go, output.go, outputdockerimage.go, outputfile.go, uploader.go
For the same output multiple upload destinations can now be specified.
So far it was only possible to specify a single upload destination of a kind per output. 
```
cfg: fix: field name in error messages related to S3Upload.Key field
When validating the app config failed because of issues with the S3Upload.Key
field the error message references the field with the name "dest_file" or
"destfile" instead of key.
Fix the field name used in the error messages
cfg: support specifying multiple file upload destinations per output
The S3Upload and FileCopy fields in the app config are changed to be being
slices instead of single elements.
This allows to specify multiple upload destination per output file …
```
=> Support specifying multiple upload destinations per output

internal/command/run.go, output.go, outputdockerimage.go, uploader.go, uploadinfo.go
```
outputdockerimage: rename field UploadDestination field to plural form
it stores multiple entries, not one
uploader: return an error when UploadDestination is nil
The field should never be nil for an OutputDockerImage.
uploadinfo: remove unused method Method() from UploadInfo interface
embed cfg struct containing upload informations instead duplicating fields
run: add comment explaining why all uploads for a task can run in same goroutine …
```
=> Smaller misc improvements

inputresolver.go, internal/resolve/gitpath/gitpaths.go, internal/resolve/resolver_test.go, internal/vcs/git/git.go
The Glob and GitPath resolvers were processing patterns differently.
For example when a '*' was used as path in the Input.GitFiles section it also matched
directory separators, when '*' was used as path in the Input.Files section it
did not match directory separators.
Ensure paths are resolved the same by resolving globs for both resolvers via fs.Glob().
The GitPath resolver is then passing the paths to "git ls-files" to check if
they are committed to the repository. The "--noglob-pathspecs" parameter is
passed to "git ls-files" to treat all paths literally.
Closes #121
Closes #113
=> resolver: use same glob syntax for Glob and GitPath resolver

cfg/app.go, cfg/dockerimageoutput.go, cfg/dockerimageregistryupload.go, cfg/filecopy.go, cfg/fileinputs.go, cfg/fileoutput.go, cfg/gitfileinputs.go, cfg/golangsources.go, cfg/include.go, cfg/includedb_test.go, cfg/resolver/envvar.go, cfg/resolver/envvar_test.go, cfg/resolver/uuidvar_test.go, cfg/s3upload.go, cfg/task.go, cfg/taskinclude.go, cfg/upgrade/v4/v4.go, cfg_resolvers.go, internal/command/testdata/var_in_include/app1/.app.toml, internal/command/testdata/var_in_include/app2/.app.toml, internal/command/testdata/var_in_include/inputs.toml, internal/command/testdata/var_in_include/tasks.toml, internal/vcs/git/git.go
This PR adds support to use the values of environment variables in fields of app config files.
Because the current syntax for variables (e.g. `$ROOT`) did not have a character that marks the end of the variable name it was not possible to do it with the syntax.
The syntax for all variables is changed to use the common template syntax.
- `$ROOT` became `{{ .root }}`,
- `$APPNAME` became `{{ .appname }}', etc.
- The cfg upgrader is changed to replace all variables in config fields in the old syntax with the new one.
The syntax also provides the opportunity to switch to using to text/template` template engine of the go stdlib and provide more templating/variable options.
The value of environment variables can be specified via `{{ env <VARIABLE-NAME> }}`.
For example `{{ env SHELL }}`  is …
=> Support referencing environment variables in app config files

.circleci/config.yml, internal/vcs/git/git.go, internal/vcs/git/git_test.go
If a lot of files were resolved it could happen that running "git ls-files"
failed with: "/sbin/git: argument list too long".
When the length of the strings of the pathspecs slice that is passed to
git.LsFiles() exceeds a threshold, the function is now splitting the number of
arguments in smaller slices and invokes "git ls-files" for each of it.
As threshold "32767 - 2048" is chosen.
Windows has a limit of 32767
(https://devblogs.microsoft.com/oldnewthing/20031210-00/?p=41553).
In the exec sycalls the array for the command line arguments and the environment
variables share the same limit. Therefore 2048 is subtracted to reserve some
space for environment variables (as recommended in
https://www.in-ulm.de/~mascheck/various/argmax/).
Modern Linux/Unix systems have a much higher limit for …
=> git: fix: discovering input files fails with: argument list too long

loader.go, loader_specifiers.go
```
fail if <app>.<taskname> was passed as an argument and app has no such task
If as parameter a <app>.<task> was specified, fail if the app has no task that
matches the names.
So far it caused that "baur status" showed an empty list.
improve error message when "." is passed as arg and no .app.toml file exist
When "." was passed as argument to e.g. "baur status" it failed with:
'ERROR: could not find the following apps:'
Improve the error message, print that the current directory does not contain an
.app.toml file
```
Closes #253
=> Improve error handling when discovering apps and tasks

internal/vcs/git/git.go, internal/vcs/git/git_test.go
If none of the passed pathspecs that were passed to git.LsFiles() matched files
tracked by the git repository, the function returned a slice with one empty
string element.
This caused that baur commands failed because no digest could be calculated for
the directory.
=> git: fix: LsFiles() returned empty string as path

internal/command/diff_inputs.go, internal/command/helpers.go, internal/command/init_app.go, internal/command/init_db.go, internal/command/init_include.go, internal/command/ls_apps.go, internal/command/ls_inputs.go, internal/command/ls_outputs.go, internal/command/ls_runs.go, internal/command/run.go, internal/command/show.go, internal/command/status.go
- rename the SPEC argument to TARGET and document it in the long help output of
"baur run" and "baur status"
- in the usage output use angel-brackets only for required arguments, this is
the standard according to https://en.wikipedia.org/wiki/Usage_message
- Use an underscore instead of a hyphen to separate words in usage argument
specifiers
=> commands: improve usage output

pkg/baur/inputresolver.go, pkg/baur/inputresolver_test.go
If a FileInput list was defined as optional and one element resolved to 0 files
all following elements in the list were skipped and not resolved to any files.
Continue resolving the following element in the slice instead of returning from
the function
=> inputresolver: fix: paths skipped in slice if previous elemen did not exist

internal/command/show.go
Sort the list of config files printed by "show".
The path to the .app.toml file is always shown first, the other paths
afterwards.
This makes it easier to spot the path to the .app.toml file and prevents that
the order differs between "baur show" invocations
=> show: show the "Config Files" list sorted

internal/command/helpers.go, internal/command/init_db.go, internal/command/run.go, internal/command/status.go, pkg/baur/baur.go, pkg/baur/cfg_resolvers.go, pkg/baur/loader.go, pkg/baur/repository.go, pkg/baur/storage.go, pkg/cfg/dockerimageoutput.go, pkg/cfg/input.go, pkg/cfg/inputinclude.go, pkg/storage/postgres/query_test.go
```
unexport some function, improve godoc
cfg: do not use different set of variable resolvers for include fields
For resolving variables in config files 2 different sets of resolvers were used:
- for the "Includes" field in config only resolvers for ' {{ .app }, {{ .root }}
and {{ .env <VARNAME> }}
- all available for all other field
Remove the exception for the "Includes" field, use the same set of resolvers
then for all other fields. This simplifies the  code a bit and does not have any
real disadvantages.
This means {{ .gitcommit }} and  {{ .uuid }} variables can now be used in the
"Include" field, there is no valid usecase for it though.
---------------------------------------------------------------------- …
```
=> Small improvements, address most TODO notes

pkg/baur/loader.go, pkg/baur/loader_specifiers.go
If '*.*' was passed as spec, the loader tried to find an app named "*" instead
of returning all apps, parse and handle '*' as app name special.
If it found as app name, specs.allApps is set.
=> loader: fix: loading "*.*" failed instead of returning all tasks of all apps

internal/command/flag/buildstatus.go, internal/command/flag/datetime.go, internal/command/flag/field.go, internal/command/flag/sort.go, internal/command/ls_apps.go, internal/command/status.go, internal/command/upgrade_configs_test.go
Add a new option for the "--fields" parameter of "baur status" to show the application name in the printed table.
By default the commands does not show the application name.
This required to support specifying different default values for the flag then the supported ones.
```
usage: remove wrong angle-brackets in usage output
angle-brackets should be only used for required parameters, remove using
angle-brackets in the help output in other contexts
status: fix constants names storing task-id field option
The constants names should make it clear to which cmdline parameter field option
they belong.
Rename:
statusNameHeader -> statusTaskIDHeader
statusNameParam -> statusTaskIDParam …
```
=> status: support to show the application name

internal/command/flag/field.go
The list of supported flags should be shown in the usage output, not the smaller
set of enabled fields.
=> flags: show supported instead of enabled fields in fields flag usage

.golangci.yml, pkg/baur/output.go
Thanks exportloopref linter!
The issues it found would cause that the last upload definitions in the
config would be be run multiple times and the other ignored.
=> linters: enable exportloopref linter and fix found issues

pkg/baur/uploader.go
When an output was uploaded to S3, the UploadMethod stored in the database was
FileCopy instead of S3.
=> upload: fix: uploadMethod stored in DB for S3 was FileCopy instead of S3

internal/command/flag/field.go
The usage output showed for flag fields documentation a text like:
"where FIELD is one of: , , , , , , app-name, git-commit"
That those " ," character sequences are shown was introduced in commit f30a5a9.
A slice was accidentally preallocated with a size instead of a capacity
argument, this caused the empty slice elements.
=> usage: fix fields flag documentation

pkg/cfg/filecopy.go, pkg/cfg/fileoutput.go, pkg/cfg/upgrade/v4/v4.go
```
upgrade configs: do not create empty S3 and FileCopy output definitions
cfg: add validation to ensure Filecopy.path fields are not empty
If a Filecopy.path field is defined in a config to be an empty string, baur will
now fail with an error.
---------------------------------------
```
This closes #275
=> fix: upgrade configs might create empty S3 or filecopy output definitions

internal/command/command_test.go, internal/command/diff_inputs.go, internal/command/diff_inputs_test.go, internal/command/ls_inputs.go, internal/command/run.go, internal/command/status.go, pkg/baur/input.go, pkg/baur/inputstring.go, pkg/baur/taskstatusevaluator.go
The run, status, ls inputs, diff inputs commands now support to be passed multiple
"--input-str" parameters, each specified parameter is added as individual string
input.
=> support to pass multiple --input-str parameters

internal/command/diff_inputs.go, internal/command/diff_inputs_test.go, pkg/baur/inputs.go
```
diff inputs: add --input-string inputs only to first specified task/run
When the "input-string" parameter was passed to "baur diff inputs", the input
string was added to both targets that were specified.
Both runs always had the additional input string and therefore could not differ
regarding the string input.
Change the behavior to addd the string input that is specified as parameter only
to the first target specified by the arguments.
diff inputs: clarify arguments in usage description
```
=> diff inputs: add --input-string inputs only to first specified task/run

pkg/cfg/app.go, pkg/cfg/app_test.go, pkg/cfg/taskdef.go, pkg/cfg/tasks_test.go, pkg/cfg/validation.go
The configuration file validation will now fail if an app or task name contains
a reserved character that has a special meaning on the cmdline or in values of
other configuration fields.
=> cfg: check if task or app-names contain reserved characters

internal/command/ls_runs.go, internal/command/ls_runs_test.go, internal/command/storageinputwrapper.go, pkg/baur/inputfile.go, pkg/baur/inputstring.go, pkg/baur/storage.go, pkg/storage/filter.go, pkg/storage/postgres/filters_sorters.go, pkg/storage/postgres/insert.go, pkg/storage/postgres/insert_test.go, pkg/storage/postgres/query.go, pkg/storage/postgres/query_test.go, pkg/storage/postgres/schema.go, pkg/storage/storage.go
```
tests: add testcase "baur ls runs --has-input"
storage: refactor input string representation
File Input and String Inputs were represented by the same storage struct
and also stored in the same postgresql table.
In the input.name db column and in the storage.Input.Name struct field was
stored for file inputs the path, for string inputs the string with a "string:"
prefix.
The input table had a unique constraint for the name and digest column, that was
used to to a database upsert operation (only insert if records does not exist).
When long string inputs were specified as parameters for "baur run" it happened
that the input could not be stored in the table because it was too long to be
stored in the unique …
```
=> storage: refactor input string representation

pkg/cfg/fileinputs.go, pkg/cfg/golangsources.go, pkg/cfg/inputinclude.go, pkg/cfg/task.go, pkg/cfg/taskinclude.go
Improve the comments in the configuration files that can be generated via
"baur init"
=> cfg: improve comments in example configuration files

internal/command/show.go
All field values were printed highlighted/colored by "baur show" except the
"Upload Duration", also highlight it's value.
=> show: fix: upload duration not printed colored

internal/command/util_test.go, internal/log/log.go
When a testcase was calling redirectOutputToLogger() and the following executed
testcase wasn't, all it's output was redirected to the logger for the first
testcase.
These log messages could be lost or associated with the wrong testcase.
Fix it by resetting the log streams that were changed to their previous values
when the test finished execution.
=> tests: reset log, stdout, stderr streams when a test finishes

internal/command/command_test.go, internal/command/status_test.go, internal/command/testdata/multitasks/.baur.toml, internal/command/testdata/multitasks/app3/.app.toml, internal/command/testdata/multitasks/app3/build.sh, internal/command/testdata/multitasks/app3/check.sh, internal/command/testdata/multitasks/dir1/app1/.app.toml, internal/command/testdata/multitasks/dir1/app1/build.sh, internal/command/testdata/multitasks/dir1/app1/check.sh, internal/command/testdata/multitasks/dir1/app2/.app.toml, internal/command/testdata/multitasks/dir1/app2/build.sh, internal/command/testdata/multitasks/dir1/app2/check.sh, internal/command/testdata/multitasks/dir2/app4/.app.toml, internal/command/testdata/multitasks/dir2/app4/build.sh, internal/command/testdata/multitasks/dir2/app4/check.sh, internal/command/util_test.go, pkg/baur/loader.go, pkg/baur/loader_specifiers.go
```
loader: fix: a task spec with only a wildcard for the app loaded all tasks
If a task specification was passed to "baur status" or "baur run" that consisted
of a wildcard for the app and a specific task-name like '*.build', all tasks for
all apps were loaded,  instead of only all tasks matching the task-name.
Fix it by removing the specs.allApps fields.
It is not necessary because if a spec is parsed with an non-empty task part an
element for it is added to specs.taskSpecs and it will then be loaded by
Loader.tasks().
loader: rename appTask() to appTaskByName()
The new name should be more clear
loader: improve debug log message …
```
=> loader: fix: a task spec with only a wildcard for the app loaded all tasks

internal/command/run.go, internal/command/run_test.go, internal/exec/command.go
Add a new cmdline parameter to "baur" run, that if passed prints the stdout and
stderr output of executes commands to the console.
This was only possible by passing the "--verbose" parameter so far, which also
printed tons of other noisy output.
Closes #140 
Related: https://github.com/simplesurance/baur/issues/328
=> run: add parameter --show-task-output

README.md
Updated readme docker run for postgres as using the example command fails with - 
"Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run"."
=> Add password env variable to docker run

internal/routines/pool.go, internal/routines/pool_test.go
```
routines: fix: race on pool shutdown
There was a chance that when Wait() and Queue() was called in parallel, that
the work was not executed before the pool terminated and neither Queue() paniced
because it was called after the pool terminated.
Hold the lock while dequeuing work from the queue and checking if p.terminate is
set.
routines: fix: work was processed in LIFO instead FIFO order
The go-routine pool processed work in LIFO instead of FIFO order as it is
documented.
```
=> routines: fix issues in the go-routine pool implementation

.circleci/config.yml, .golangci.yml, pkg/cfg/cfg.go, pkg/cfg/inputinclude.go, pkg/cfg/outputinclude.go, pkg/cfg/taskinclude.go, pkg/storage/postgres/insert.go
```
remove redundant redundant if ...; err != nil checks
After switching from golint to revive, some new redundant if err checks were
found, remove them
circleci: update golangci-lint and go
golang 1.16.5
golangci-lint 1.41.1
golangci-lint: replace golint with revive
This fixes:
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to:
The repository of the linter has been archived by the owner.
Replaced by revive.
```
=> CI: Update golangci-lint and golang, replace golint with revive linter

internal/command/run.go
```
run: only log "waiting for uploads to finish" when "-s" was not passed
When the --skip-upload parameter was passed to "baur run", it was printing to
the console "task execution finished, waiting for uploads to finish...".
Despite it did not upload anything.
- Only print this message and call uploadRoutinePool.Wait() when the cmdline
parameter "--skip-upload" is not passed.
- only create the uploadRoutinePool pool if c.skipUpload is false, if it is true
it is not used
```
=> run: only log "waiting for uploads to finish" when "-s" was not passed

.circleci/config.yml
- Update the tools used in CI to go 1.18
- The minimum required version in the go.mod file will be set to 1.18, when 1.18 features are used
=> ci: update to go 1.18

pkg/cfg/app.go
When "baur init app" was run the generated app config contained invalid template
variables.
The variables use the syntax of baur v1 which are not supported anymore.
Update the baur template variables in the generated example config to match the
baur v2 equivalents.
=> init app: fix wrong template variable names in generated example config

internal/resolve/gosource/gosource.go, internal/resolve/gosource/gosource_test.go, internal/resolve/gosource/testdata/embedded_file/embed_test.go, internal/resolve/gosource/testdata/embedded_file/hello_test.txt, internal/resolve/gosource/testdata/embedded_file/test_config.json
```
resolve/gosource: add testcase for embedding files in go testcases
Test in the embedded_file testcase for golang source resolver if files that are
embedded in testcases are also resolved.
resolve/gosource: log withTests setting with debug priority
When running baur with "--verbose" flag, the golang source resolver now also
logs if go testcases are included in the result.
resolve/gosource: redirect log output to test logger in testcases
This ensures that output can be correlated to the correct testcase.
```
=> resolve/gosource: add testcase for embedding files in go testcases

internal/fs/fileglob.go, internal/fs/fs.go, internal/testutils/repotest/repotest.go, pkg/baur/repository.go
```
repository: use consistent path representation in error message
The error messages returned from NewRepository sometimes quoted the path
sometimes they did not, always quote it.
fix TestDifferencesOutputWithCorrectState failed on Windows
In the Windows CI machine os.MkdirTemp() returned a short DOS Path to the temp
directory used as repository directory.
When input files were resolved, the long path to the repository directory was
used.
This caused that the paths used different representations of the same directory
in TestDifferencesOutputWithCorrectState(), comparing their string
representation failed, they were not equal.
This is the same issue that was fixed in commit
"repository: use canonicalized repo …
```
=> fix TestDifferencesOutputWithCorrectState test fails on windows

pkg/baur/repository_test.go
The TestNewRepositoryUsesRealPaths failed on Windows because the tempDir path was a short DOS Directory path.
The test expects that the tempdir path is the realpath and the same then the paths used in the Repository struct.
=> tests: use temp dir realpath in TestNewRepositoryUsesRealPaths

internal/fs/fs.go, internal/fs/fs_test.go
address the Todo note that FindFileInparentDirs() might not have been able to detect the root path on all OSes.
This is achieved by:
- using filepath.Dir() to get the path to the parent directory instead of using "..", which might also not have been worked on all OSes. filepath.Dir() returns a path ending in os.PathSeparator only when it is the root path, this is used to detect the root path.
- To prevent that the search aborts too early if an unclean path ending in a PathSeperator is passed as startPath, filepath.Clean() is called on the startPath now
=> fs/FindFileInparentDirs: ensure search ends on root path os independent

internal/testutils/repotest/repotest.go, pkg/baur/inputfile.go, pkg/baur/inputfile_singletoncache.go, pkg/baur/inputfile_singletoncache_test.go, pkg/baur/inputfile_test.go, pkg/baur/inputresolver.go
```
inputfile: accept absolute path instead of repoRelPath in constructor
Change NewInputFile() InputFileSingletonCache.CreateOrGetInputFile() to accept
the absolute path to the file instead of the absolute repository path and relative file path.
The methods created the absolute path from both of these arguments and only used
the absolute and relative path.
The caller (InputResolver) already has the absolute path and can pass it
directly. This prevents redundant filepath.AbsPath() calls.
This is a breaking change. It changes the baur package API.
inputfile: use singleton pattern for input file
Instantiate an InputFile struct only once per file.
Previously if multiple apps had the same file defined as …
```
=> inputfile: hash each file only once

pkg/baur/inputresolver.go, pkg/baur/inputresolver_cache.go, pkg/cfg/fileinputs.go, pkg/cfg/golangsources.go
```
inputresolver: cache glob file results per path
An FileInput section in a config file, can contain multile Path specifications.
The input resolver cache was caching results for a while FileInput section.
Each path in a FileInput section was resolved separately though.
Multiple apps can have FileInputs sections that contain the same path with the
same options.
To improve caching, cache the results per path of a FileInput.
cfg: add reminder comment to inputfile structs
Add a comment to remind the person who might modify the attributes of Inputs
specification in the future, to adapt the inputresolver cache also.
```
merge after …
=> inputresolver: cache glob file results per path

internal/fs/fileglob.go, pkg/baur/inputresolver_unix_test.go
```
tests/inputresolver: add tests for glob patterns matching broken symlinks
Add 2 testcases were "**" glob patterns are used in directories that only
contain broken symlinks.
fs/glob: use AbsPath when keeping track of the already visited directories
Use the AbsolutePath of a directory to keep track of the visited ones.
This should prevent that directories are visited twice because different
representations of the same path are used.
inputfiles: do not resolve directory symlinks
When an InputFile Glob matched a directory that was a symlink, the symlink was
resolved and the resolved directory path was returned.
Do not resolve …
```
=> inputfiles: improve globbing

internal/command/show.go, internal/command/show_internal_test.go
```
show: remove trailing whitespace for slice types
When "baur show" printed a slice type that had  >=2 values, each element was
separated with ", \n".
Change the separator to ",\n"
show: fix: output of input slice types is broken
ec95560 broke the "baur show" output, if an input slice had >1 elements, the
field was printed multiple times, each line repeating the previous input + one
additional one.
Use again a separate slice containing the indentation elements, instead of
appending the output for each row to it.
This commit also adds a testcase for mustWriteStringSliceRows().
```
=> show: fix: output of input slice types is broken

pkg/storage/postgres/client.go, pkg/storage/postgres/insert.go, pkg/storage/postgres/migrations/1.sql, pkg/storage/postgres/schema.go, pkg/storage/postgres/schema_test.go, pkg/storage/postgres/schema_unit_test.go
```
storage: support applying schema migrations
This commit adds support to change the database schema via migrations.
Schema migrations are stored in the embedded FS pkg/storage/postgres/migrations.
They are named as <VERSION>.sql. <VERSION> must be an int32 >=1.
The initial db schema that was stored as a constant in schema.go is moved to
pkg/storage/postgres/migrations/1.sql.
The migrations files are read and the filename is parsed when Init() or
ApplyMigrations() is called.
Init() applies all found migrations files.
ApplyMigrations() only applies the migrations that have a version that is
smaller then schema version stored in the database.
ApplyMigrations() will be used in a following commit. …
```
=> storage: support applying schema migrations

internal/command/run_test.go, internal/command/show.go, internal/command/status.go, internal/command/storageinputwrapper.go, internal/command/util_test.go, pkg/baur/inputenvar.go, pkg/baur/inputresolver.go, pkg/baur/inputresolver_test.go, pkg/baur/storage.go, pkg/cfg/app.go, pkg/cfg/envinputs.go, pkg/cfg/include.go, pkg/cfg/input.go, pkg/cfg/inputdef.go, pkg/cfg/inputinclude.go, pkg/storage/postgres/insert.go, pkg/storage/postgres/migrations/2.sql, pkg/storage/postgres/query.go, pkg/storage/postgres/query_test.go, pkg/storage/postgres/schema.go, pkg/storage/storage.go
This commits adds support to track the value of environment variables as Input. As all other inputs, they can be defined in an include or app configuration file.
The .app.toml configuration sections looks like:
```toml
[[Task.Input.EnvironmentVariables]]
names = [
"APP_VERSION",
"PAYMENT_APP_*",
]
optional = false
```
Environment variables names can contain go glob patterns. This allows to track all variables that a certain patterns without having to list each of them. If the optional flag is true, baur command that calculate app inputs (baur status, baur run, etc) will fail if no environment variable is defined matching the defined pattern.
Declared but undefined environment variables are treated as non-existing.
The values of environment variables is not stored in the database or shown …
=> inputs: support tracking environment variables

go.mod, go.sum, internal/command/helpers.go, internal/command/init_db.go, internal/command/upgrade_db.go, internal/command/upgrade_db_test.go, pkg/storage/postgres/schema.go, pkg/storage/postgres/schema_test.go, pkg/storage/postgres/schema_unit_test.go, pkg/storage/storage.go, vendor/github.com/simplesurance/baur/v2/LICENSE, vendor/github.com/simplesurance/baur/v2/pkg/storage/filter.go, vendor/github.com/simplesurance/baur/v2/pkg/storage/postgres/client.go, vendor/github.com/simplesurance/baur/v2/pkg/storage/postgres/errors.go, vendor/github.com/simplesurance/baur/v2/pkg/storage/postgres/filters_sorters.go, vendor/github.com/simplesurance/baur/v2/pkg/storage/postgres/insert.go, vendor/github.com/simplesurance/baur/v2/pkg/storage/postgres/logadapter.go, vendor/github.com/simplesurance/baur/v2/pkg/storage/postgres/query.go, vendor/github.com/simplesurance/baur/v2/pkg/storage/postgres/schema.go, vendor/github.com/simplesurance/baur/v2/pkg/storage/storage.go, vendor/modules.txt
Implement a new baur subcommand (`baur upgrade db`) to upgrade the database schema to a newer version.
The public storage API is extended for methods to upgrade db and get the current and required schema version.
Testcases for the `upgrade db` command are added, which are creating a database schema via the baur 2.x packages and then upgrading the db.
See commit messages for more details
=> implement "baur upgrade db" command

internal/fs/fileglob.go, internal/fs/fs.go, pkg/baur/inputresolver.go, pkg/cfg/fileinputs.go
```
fs/AbsPaths: use array indexing instead of append in AbsPaths()
it is faster
fs/AbsPaths: only join relative paths
AbsPaths() is changed to only join paths elements that are not absolute paths.
This will allow to call the functions with a paths slice that contain absolute
and relative paths.
fs/fileglob: do not call filepath.Abs()
Removing calling filepath.Abs() in FileGlob().
It is unnecessary for our usecase.
The paths returned by doublestar are absolute if an pattern is passed with an
absolute path, which baur is always doing.
inputresolver: …
```
=> inputresolver: improve caching + minor improvements

.github/workflows/build.yml, .github/workflows/golangcilint.yml, .github/workflows/test.yml
```
ci: update golangci-lint to 1.50.*
ci: update go to 1.19.13
ci/windows: run tests without "-v" flag
Run the tests without "-v" parameters, as we do in all other CI tasks already.
"-v" generates to much output, making it hard to find the relevant messages when
a test failed.
```
=> ci: update tools & don't run tests with '-v'

internal/command/init.go, internal/command/init_bashcomp.go, internal/command/init_fishcomp.go, internal/command/init_powershellcomp.go, internal/command/init_zshcomp.go
Add support to generate shell completion scripts for zsh, fish and powershell.
See the commit messages for details.
=> support shell completion for zsh, fish and powershell

internal/command/completion.go, internal/command/diff_inputs.go, internal/command/init_app.go, internal/command/init_bashcomp.go, internal/command/init_db.go, internal/command/init_fishcomp.go, internal/command/init_powershellcomp.go, internal/command/init_repo.go, internal/command/init_zshcomp.go, internal/command/ls_apps.go, internal/command/ls_inputs.go, internal/command/ls_outputs.go, internal/command/ls_runs.go, internal/command/run.go, internal/command/show.go, internal/command/status.go, internal/command/upgrade_configs.go, internal/command/upgrade_db.go
This PR adds support for completing arguments for all baur commands.
If the baur command is run in a baur repository, the configuration files are passed and the available apps, tasks and directories containing apps are used for completion.
Completing to arguments that must be fetched from the database, e.g. run-ids or task-id for `ls runs` is not implemented in this PR.
```
completions: complete "ls runs" args to app and task-ids
Support to complete argument pass to "ls runs" to task-ids.
completions: disable file completions for "ls outputs"
"ls outputs" only supports database IDs as argument, do not offer completions to
filenames and directories.
--------------------------------------------------------------- …
```
=>  shell completions: support arg completion 

internal/command/show.go
"baur show" always printed a "Type: Excluded Files" line
Only show it if files are excluded, otherwise omit the section, as it is done for all other sections.
=> show: do not show Excluded Files section if it is empty

internal/exec/command.go, internal/exec/command_pdeathsig_supported.go, internal/exec/command_pdeathsig_unsupported.go, internal/exec/pdeathsig_test.go
When baur executes a task and the baur process gets killed, the task subprocess continues to run. This was reproduced on Linux, on other OSes it was not tested but they are probably also affected.
Prevent that this can happen by setting Pdeathsig for the executed process. If the parent thread is killed, the specified signal (SIGKILL) will be sent to the child.
Pdeathsig is sent when then parent thread dies, to prevent that thread on which the go-routine ran that started the process dies, runtime.LockOSThread is called[^1].
This fixes the issue only on Linux and FreeBSD.
Windows & Darwin do not have Pdeathsig in their SysProcAttrs. To achieve the same on Windows support for job objects in Golang might be needed[^2].
[^1]: https://github.com/golang/go/issues/27505#issuecomment-418800861 …
=> run: ensure task process is killed when baur terminates

go.mod, go.sum, pkg/baur/init_test.go, pkg/baur/inputresolver_unix_test.go, pkg/baur/loader.go, pkg/baur/loader_test.go, pkg/baur/testdata/app_matches_multiple_app_dirs/app1/.app.toml, vendor/golang.org/x/exp/LICENSE, vendor/golang.org/x/exp/PATENTS, vendor/golang.org/x/exp/maps/maps.go, vendor/modules.txt
loader: deduplicate application_dirs
If the application_dirs configuration contains the same directory multiple
times, baur searched for app config files in it multiple times. This operation
can be quite costly. Deduplicate application_dirs and log a debug message if
duplicates are found.
loader: fix that the same app can be discovered multiple times
If an application directory is matched by multiple entries in
application_directories from the .baur.toml file, "baur ls apps" and "baur
status" would show it multiple times.
Fix it by deduplicating the list of discovered application configs.
=> loader: fix that the same app can be discovered multiple times

.github/workflows/golangcilint.yml
ci: increase golangci-lint timeout
golangci-lint started to fail because it timed out since it was updated.
Increase the timeout from 1m to 3m.
=> ci: increase golangci-lint timeout

internal/exec/command.go
By default the log function was an function that did nothing. If logFn was not nil, the output was always splitted in lines and logged via logFn. This is unnecessary.
Instead of setting DefaultLogFn to an noop function, set it to nil. This allows to determine if logFn is set and prevent unnecessary processing of the stdout and stderr of the process.
=> exec: only stream output when log function is set

.golangci.yml, internal/command/diff_inputs.go, internal/command/ls_outputs.go, internal/command/ls_runs.go, internal/command/show.go, internal/exec/command.go, internal/fs/fs.go, internal/testutils/logwriter/logwrap.go, internal/upload/docker/docker.go, internal/version/version.go, pkg/baur/cfgupgrade.go, pkg/baur/taskstatusevaluator.go, pkg/cfg/fielderror.go, pkg/cfg/taskdef.go, pkg/storage/postgres/query.go
adapt code to errorlint suggestion
Adapt the code to the errorlint suggest.
Using errors.Is/As is often unnecessary in the current code but it will make the
code more resilient if code is changed to wrap errors instead.
golangcilint: enable errorlint linter
=> golangcilint: enable errorlint linter

pkg/baur/inputresolver_test.go, pkg/baur/inputresolver_unix_test.go
Add several testcases for the InputResolver, that verify that a change is detected when:
- file content changes,
- a symlink is replaced by it's target,
- target path of a symlink changes but the target file content stays the same,
- content of a symlink target changes,
- file permissions change,
- file owner changes
Several of the tests are failed.
They are disabled and GitHub issues for it have been created.
=> tests: add file and symlink inputresolver testcases

internal/exec/command.go
When an error happened writing the output of the command to the MultiWriter, the last output is missing in the error message.
Reorder the MultiWriters, to first write to the stdoutPss, stderrPss writer that are the buffers for the error message.
That way the buffers contain the last output if a write operation to the following writers fail.
=> exec: fix: command output not shown when MultiWriter fails

internal/command/run.go, internal/exec/command.go, internal/exec/command_linux_test.go, internal/exec/command_test.go, internal/exec/result.go
```
exec: include stream name and WARN: in outputstream log messages
If an error happens when streaming the output, always include the stream name
and WARN in the related log message.
Some internal variable names are also shortened.
tests: add simple exec stdout streaming testcase
exec: fix: duplicate newlines in streaming output
When "--verbose" was passed to "baur run" the logger was used as logf function.
The logger appends a "\n" when the last character is not already a newline.
Because "\n" character was colorized with the logFnStderrStreamColorfn, the
logger did not detect the newline anymore and appended a second one.
Do not …
```
=> exec: improve information on command execution error

internal/upload/s3/s3.go
For artifacts that are uploaded to S3 baur now stores it s3://BUCKET/OBJECT-ID URI in the database, instead of the path-style S3 URI.
The s3:// URI can directly be used with the S3 command line tools. The path-style can not, it is not supported by the "aws s3" cli.
=> s3: Store s3:// instead of https:// in db for uploaded objects

internal/command/helpers.go, internal/command/run.go, internal/command/run_test.go, internal/command/status.go, internal/command/status_test.go, internal/command/term/streams.go, internal/prettyprint/prettyprint.go, internal/vcs/git/git.go, internal/vcs/git/repository.go, internal/vcs/novcsstate.go, internal/vcs/state.go, pkg/baur/taskrunner.go, pkg/baur/taskrunner_test.go
Add a new flag to "baur run" and "baur status" called --require-clean-git-worktree.
If passed, the commands fail if the baur repository contains untracked or modified tracked git files, this includes files that are in .gitignore.
"baur run", checks the state on start and before executing a task, to catch cases were multiple tasks are run and of them modifies or creates new files in the git repository.
This helps to ensure that tasks are executed in an clean reproducible environment.
Closes #142
=> add --require-clean-git-worktree flag to run and status commands

internal/command/diff_inputs.go, internal/command/ls_inputs.go, internal/command/run.go, internal/command/status.go, internal/digest/digest.go, internal/digest/gitobjectid/gitobjectid.go, internal/digest/gitobjectid/gitobjectid_test.go, internal/digest/sha384/sha384.go, internal/testutils/repotest/repotest.go, internal/vcs/git/files.go, internal/vcs/git/git.go, pkg/baur/inputfile.go, pkg/baur/inputfile_singletoncache.go, pkg/baur/inputfile_singletoncache_test.go, pkg/baur/inputfile_test.go, pkg/baur/inputresolver.go, pkg/baur/inputresolver_test.go, pkg/baur/inputresolver_unix_test.go
If the baur repository is also a git repository and the git binary is available,
baur now uses git object IDs as file content digest.
The object IDs for all tracked files are read from the git repository.
If an inputfile is tracked and unmodified, the existing git object ID can be
used.
This does not work for files that are part of a git submodule.
Depending on the number of input files and hardware this can be much faster.
It saves CPU time because the digest does not need be
calculated and disk I/O because all input files don't have to be read anymore.
Only "git ls-files" needs to be executed and it's output parsed.
The digest of an InputFile is still a SHA384. It is the hash of the aggregation
of the git object id of the content and the SHA384 of it's relative file path.
If an file is …
=> inputfiles: use git object IDs as input file content digests

internal/command/diff_inputs.go, internal/command/ls_inputs.go, pkg/baur/inputresolver.go, pkg/baur/inputresolver_test.go, pkg/baur/taskstatusevaluator.go
The parameter is not needed anymore, since 2ec86012 it is stored in the InputResolver struct, remove it.
Inputresolver testcases were adapted and some also adapted to to use a subdirectory of the repositoryDir that is passed, to also test resolving of relate paths.
=> inputresolver: remove repositoryDir parameter from Resolve method

internal/command/helpers.go, internal/command/init_db.go, internal/command/upgrade_db.go
Use the newly added fatal function and fatalf equivalent, instead of creating a new error only to be able to call stderr.ErrPrintln
=> command: use fatal function, add fatalf equivalent and use it

internal/command/helpers.go, internal/command/root.go, internal/command/show_test.go
Add a new "--repository" parameter to all baur commands. As value the path to a baur root repository can be passed.
This can be used to run baur from outside a baur repository, which can be sometimes in scripts.
=> Add global --repository parameter

internal/command/diff_inputs.go, internal/command/ls_inputs.go, internal/command/run.go, internal/command/status.go, internal/digest/gitobjectid/gitobjectid.go, pkg/baur/inputresolver.go, pkg/baur/inputresolver_test.go
disable calculating git object ids on --require-clean-git-worktree
When --require-clean-git-worktree is specified as commandline parameter, disable
calculating git object IDs for files that were not returned "git ls-files".
This is a safe guard, to ensure that only git object IDs are used that already
exist in the git repository, calculating them manually is expensive.
gitobject: query db always for resolved symlink paths
If a path for that the digest was requested contained a directory symlink, the
file was not found in the db, despite it contains an entry for the symlink
target path.
gitobject only resolved paths to symlinks if "git ls files" returned a symlink
stauts for them. It's only returned for …
=> gitobject: query db always for resolved symlink paths + disable calculating git object ids on --require-clean-git-worktree

internal/command/command_test.go, internal/command/flag/format.go, internal/command/status.go, internal/command/status_test.go, internal/command/upgrade_configs_test.go
status now supports to print the information in JSON format.
The format can be selected via the new parameter "--format", it accepts "plain",
"csv" and "json" as value.
In the JSON output fields that are not specified via "--fields" are omitted.
Fields that have no value, e.g. RunID when a task status is pending, is nil.
Because we want to distinguish between fields that should be omitted, fields
that undefined and empty values, we can not marshal a struct directly. It can
not distinguish between omitted fields and undefined fields.
To realize that the structs holding the output data is converted to a map and
then marshaled, fields that are omitted are not added to the map.
--format replaces the previous "--csv" parameters.
The "--csv" parameter for status is deprecated.
Example:
```
$ …
```
=> status: support JSON output format

internal/command/command_test.go, internal/command/diff_inputs.go, internal/command/helpers.go, internal/command/ls_apps.go, internal/command/ls_apps_test.go, internal/command/ls_inputs.go, internal/command/ls_outputs.go, internal/command/ls_runs.go, internal/command/show.go, internal/command/status.go, internal/command/util_test.go, internal/format/format.go, internal/format/json/json.go
Similar to the implementation for "baur status", add support for JSON format to
"baur ls apps".
The --csv parameter is deprecated.
Closes #504
=> ls apps: support json format

internal/command/root.go
Change the autocompletion for the --repository flag to only suggest directory names.
=> completion: limit --repository completion to directory names

internal/command/ls_apps.go, internal/command/ls_outputs.go
Similar to the implementations for "ls apps" and "status", "ls outputs" now
supports JSON format.
The --csv flag is deprecated.
Closes #506
=> ls outputs: support json format

internal/fs/fs_nonunix.go, internal/fs/fs_unix.go, internal/testutils/repotest/repotest.go, pkg/baur/inputfile.go, pkg/baur/inputfile_test.go, pkg/baur/inputresolver.go, pkg/baur/inputresolver_test.go, pkg/baur/inputresolver_unix_test.go
On Unix systems baur now tracks the executable owner bit of files.
This enables that tasks are rerun if the executable owner bit changes.
The normal use case is to clone a git repository in CI and then run
baur.
Git only tracks the executable owner bit, other permission changes are not
stored and applied. Therefore baur also only tracks the same information.
If the file is a tracked, unmodified git object the permission mode is taken
from git otherwise stat/lstat are called to obtain them after input file
discovery.
On non Unix systems the information if a file is executable is not tracked. It's
not easily obtainable via the Golang stdlib.
=> inputs: track executable permission of file owner on unix

internal/command/run_test.go, internal/exec/command.go, internal/fs/fileglob.go, internal/testutils/fstest/fstest.go, internal/vcs/git/files.go, internal/vcs/git/files_test.go, pkg/baur/inputfile.go, pkg/baur/inputresolver.go, pkg/baur/inputresolver_test.go, pkg/baur/inputresolver_unix_test.go
```
inputresolver: extend tests to if git object is not found for file
If files are added to git in a testcase configured the InputResolver to not hash
untracked files, this ensures that tests fail if a git object should be found
for a path but isn't.
inputresolver: fix: git objects for files in symlinked directory not found
Since "inputfiles: track symlink target paths" (e834583c), git objects for files
in a symlinked directory were not found anymore.
It was caused by multiple issues:
- it was only checked if the last component of the path was a symlinked, if
another component was, it was missing to resolve the realpath and try another
lookup in the gitTrackedDb
- When the gitTrackedDb was queried and the …
```
=> inputresolver: fix: git objects for files in symlinked directory not found

internal/command/ls_outputs.go, internal/command/status.go
ls outputs: change bytes and duration JSON types to numerical ones
Instead of using string as types for duration (seconds) and Bytes, use a float
for the duration and an uint64 for bytes.
status: change RunID JSON type from int to string
It is an opaque type that should also support non numerical characters, change
the RunID type in JSON format to string.
=> status + ls outputs: improve JSON field types

internal/command/run.go
When executing a task command failed and the error isn't an ExitCodeError, ErrTaskRunSkipped and neither a ErrUntrackedGitFilesExist error a nil pointer dereference panic happened.
In the stderr.Printf() call a nil result pointer was accessed. Do not access result if err is != nil, it is always nil in this case.
=> run: fix: panic on some exec errors

pkg/storage/postgres/migrations/3.sql
Delete the task_run_file_input_task_run_id_idx, idx_task_run_string_input, idx_task_run_output_task_run_id database indices.
The fields that they index are already covered by unique indices.
Closes #551
=> storage: drop duplicate indices

pkg/storage/postgres/client.go
Before connecting to the postgresql server, log that the connection is established with the redacted postgresql url as debug message.
=> postgres: log redacted postgresql connect debug message

internal/command/init_db.go, internal/command/upgrade_db.go
Support to pass the POSTGRESQL URL to that baur connects for the "upgrade db"
operation as argument.
This aligns it with the usage of "baur init db".
Passing the URL is useful when the baur repository configs only contains the
credential for a read only user.
=> upgrade db: support to pass postgresql URI as argument

pkg/storage/postgres/insert.go
insertTaskRunInputStringsIfNotExist() preallocates ~2x the memory for the inputStringIDs args than needed.
Change it to only preallocate as much memory as needed.
=> storage: fix: too much memory preallocated for query args

internal/command/release_create.go, internal/command/release_test.go, pkg/baur/loader.go, pkg/cfg/validation.go
```
loader: fix: duplicate apps and tasks are returned
Since commit 6151b481 (loader: simplify code by using set datatype,
2024-04-08) duplicate Apps and Tasks are returned by the Loader if
multiple specs matches the same app or tasks.
This results in duplicate results in "baur status" "baur ls runs" and
duplicate task executions.
Deduplicate Tasks again by task id and apps by their path.
release create: support to pass comma separated includes
Support to pass a comma-separated list of task names to "baur release
create --include".
This makes it a bit easier to use, then having to pass the "--include"
arg per task.
cfg: forbid …
```
=> release create: support to pass comma separated includes

internal/fs/fs.go, pkg/baur/errors.go, pkg/baur/loader.go, pkg/baur/loader_test.go, pkg/baur/testdata/duplicate_app_names/.baur.toml, pkg/baur/testdata/duplicate_app_names/app1/.app.toml, pkg/baur/testdata/duplicate_app_names/app2/.app.toml
```
loader: use maps.Values() function
loader: fail if app names are not unique
Having multiple apps with the same app name is error prone.
When configuration files are loaded and the specifier is not
app-specific, fail if multiple app configs are found that use the same
app name value.
When loader specifiers are passed that are specific for an app like a
task id or "<APP-NAME>.*" multiple app configs defining the same app
name are not found. This is because the loader aborts the search as soon
as the wanted app is found.
fs: remove duplicate code
call RealPath() from RealPathRel() instead of duplicating it's code …
```
=> loader: fail if app names are not unique

internal/command/command_test.go, internal/command/diff_inputs.go, internal/command/diff_inputs_test.go, internal/command/flag/format.go, internal/command/flag/oneof.go, internal/command/ls_apps.go, internal/command/ls_apps_test.go, internal/command/ls_inputs.go, internal/command/ls_inputs_test.go, internal/command/ls_outputs.go, internal/command/ls_runs.go, internal/command/ls_runs_test.go, internal/command/run_test.go, internal/command/status.go, internal/command/status_test.go, internal/command/upgrade_configs_test.go
```
commands: replace --csv flags with --format
- replace --csv flag in all commans with --format=csv
- remove the deprecated --csv flags
command: introduce OneOf flag
Refactor the implementation of the format flag to be a generic OneOf
string flag.
This will allow to reuse it for format flag parameters that only support
a subset of formats.
```
=> commands: replace --csv flags with --format

internal/command/flag/datetime.go, internal/command/flag/datetime_test.go, internal/command/ls.go, pkg/storage/storage.go
storage: fix: minor issues in godoc
ls: replace "builds" with "runs" in usage
ls runs: fix: before and after times without TZ are in UTC
When timestamps are passed to the --before or --after flags they are
interpreted as being in the UTC timezone instead in local time.
=> ls runs: fix: before and after times without TZ are in UTC

internal/command/init_db.go
Specifying the postgresql url via the BAUR_POSTGRESQL_URL environment variable only works when a baur repository config file exist. When the repository config file is not found, it fails with an error.
This is not intentional, skip searching and reading the repository config if the BAUR_POSTGRESQL_URL environment variable is set.
=> init db: fix: specifying env db url requires repo config file

internal/command/cleanup_db.go, pkg/storage/postgres/delete.go
On big databases "baur cleanup db" is running hours.
This PR introduces multiple changes to speed up the deletion.
See the commit messages for details.
=> baur cleanup db: speed up deletion

internal/command/run_test.go, internal/exec/command.go, internal/exec/command_test.go, internal/exec/result.go, pkg/baur/taskrunner.go
baur does not terminate when it runs multiple tasks and the execution of one failed.
This is the intended behavior but the check in the TaskRunner is missing, add it.
Closes #609
=> run: fix: run not aborted when task execution fails

internal/command/upgrade_configs.go, pkg/baur/cfgupgrade.go
When "baur upgrade configs" is run for configuration files that are in the latest version, the command fails with an error message stating that configs can only be upgraded from version 5 or 6.
Failing when everything is fine is confusing.
Succeed instead and print that the configs are already up to date and nothings needs to be done.
=> upgrade configs: succeed with a clear message when cfgs are up to date

pkg/cfg/app.go
The example configuration created by "baur init app" contained 2 mentions with wrong casing of the ".AppName" variable and of the "env" function.
Correct both, function names are all lowercase, variables are PascalCase.
=> cfg: fix: wrong casing of template var and func in example config

internal/resolve/gosource/gosource.go, internal/resolve/gosource/testdata/go_mod_non_vendored_deps/test_config.json, pkg/baur/inputfile.go
This fixes that when the Gosource input resolver is used on a Go
application that uses non-vendored 3. party packages, baur fails with:
ERROR: [..] evaluating task status failed: Rel: can't make
$GOMODCACHE/[..] relative to /home/[...]
Imported 3. party packages that aren't vendored are stored by Go in the
GOMODCACHE directory.
When the Gosource resolver resolves a task to sources in the GOMODCACHE,
it replaces the path to the GOMODCACHE in the input file path with
'$GOMODCACHE'. This is done to always have the same reproducible input
files paths, independent of what the actual GOMODCACHE directory is.
The inputresolver afterwards tries to evaluate the repository relative
path of the input file containing the '$GOMODCACHE' which fails with the
error.
The real path to the input file is not …
=> resolve/gosource: remove files in GOMODCACHE from discovered inputs
